# Dockerfile.nginx
FROM nginx:alpine

# Copier le fichier de configuration Nginx dans le conteneur
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80 (HTTP)
EXPOSE 80
